export type PetProps = {
  name: string;
  species: string;
  adopted: boolean;
  age: number;
};

export const pets: PetProps[] = [
  { name: "Milo", species: "Dog", adopted: true, age: 3 },
  { name: "Luna", species: "Cat", adopted: false, age: 1 },
  { name: "Bella", species: "Dog", adopted: true, age: 5 },
  { name: "Oliver", species: "Cat", adopted: true, age: 2 },
  { name: "Max", species: "Dog", adopted: false, age: 4 },
  { name: "Cleo", species: "Rabbit", adopted: true, age: 2 },
  { name: "Charlie", species: "Dog", adopted: false, age: 6 },
  { name: "Nala", species: "Cat", adopted: true, age: 3 },
  { name: "Buddy", species: "Dog", adopted: true, age: 7 },
  { name: "Daisy", species: "Guinea Pig", adopted: false, age: 1 },
  { name: "Rocky", species: "Dog", adopted: true, age: 4 },
  { name: "Lily", species: "Cat", adopted: false, age: 2 },
  { name: "Cooper", species: "Dog", adopted: true, age: 3 },
  { name: "Zoe", species: "Rabbit", adopted: true, age: 1 },
  { name: "Bear", species: "Dog", adopted: false, age: 5 },
  { name: "Simba", species: "Cat", adopted: true, age: 4 },
  { name: "Duke", species: "Dog", adopted: false, age: 2 },
  { name: "Penny", species: "Guinea Pig", adopted: true, age: 3 },
  { name: "Zeus", species: "Dog", adopted: true, age: 6 },
  { name: "Willow", species: "Cat", adopted: false, age: 1 },
  { name: "Toby", species: "Dog", adopted: true, age: 8 },
  { name: "Ruby", species: "Parrot", adopted: false, age: 5 },
  { name: "Jack", species: "Dog", adopted: true, age: 2 },
  { name: "Stella", species: "Cat", adopted: true, age: 3 },
  { name: "Finn", species: "Dog", adopted: false, age: 1 },
  { name: "Hazel", species: "Rabbit", adopted: true, age: 2 },
  { name: "Ace", species: "Dog", adopted: false, age: 4 },
  { name: "Maple", species: "Cat", adopted: true, age: 6 },
  { name: "Bruno", species: "Dog", adopted: true, age: 3 },
  { name: "Piper", species: "Parrot", adopted: false, age: 7 },
  { name: "Rex", species: "Dog", adopted: true, age: 5 },
  { name: "Coco", species: "Cat", adopted: false, age: 2 },
  { name: "Thor", species: "Dog", adopted: true, age: 4 },
  { name: "Misty", species: "Guinea Pig", adopted: true, age: 1 },
  { name: "Leo", species: "Cat", adopted: false, age: 3 },
  { name: "Rosie", species: "Dog", adopted: true, age: 2 },
  { name: "Biscuit", species: "Rabbit", adopted: false, age: 4 },
  { name: "Nova", species: "Dog", adopted: true, age: 1 },
  { name: "Shadow", species: "Cat", adopted: true, age: 5 },
  { name: "Gus", species: "Dog", adopted: false, age: 6 },
  { name: "Pearl", species: "Parrot", adopted: true, age: 9 },
  { name: "Diesel", species: "Dog", adopted: false, age: 3 },
  { name: "Ivy", species: "Cat", adopted: true, age: 2 },
  { name: "Archie", species: "Dog", adopted: true, age: 4 },
  { name: "Cinder", species: "Rabbit", adopted: false, age: 1 },
  { name: "Odin", species: "Dog", adopted: true, age: 7 },
  { name: "Amber", species: "Cat", adopted: false, age: 3 },
  { name: "Samson", species: "Dog", adopted: true, age: 5 },
  { name: "Fern", species: "Guinea Pig", adopted: false, age: 2 },
  { name: "Atlas", species: "Dog", adopted: true, age: 3 },
];
